# Generated by Django 5.1.7 on 2025-07-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_image_dislikes_remove_image_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/portfolio/hair', verbose_name='images'),
        ),
    ]
